"""empty message

Revision ID: 404909a7bf76
Revises: d34b7e7d1421
Create Date: 2024-09-20 12:44:05.469204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404909a7bf76'
down_revision = 'd34b7e7d1421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head', sa.String(length=250), nullable=True))

    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('themes_autor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('autor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('themes_autor_id_fkey', 'users', ['autor_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('head')

    # ### end Alembic commands ###
