"""empty message

Revision ID: 69821aaad4eb
Revises: ceb99a931917
Create Date: 2024-09-22 19:39:35.710420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69821aaad4eb'
down_revision = 'ceb99a931917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
