"""empty message

Revision ID: 75ee3869030c
Revises: 69821aaad4eb
Create Date: 2024-09-22 21:45:57.623230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ee3869030c'
down_revision = '69821aaad4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_comment_id_fkey', type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('likes_comment_id_fkey', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
