"""empty message

Revision ID: 8400e1f91b10
Revises: 1aa0d7d9d39d
Create Date: 2024-09-20 13:45:53.190135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8400e1f91b10'
down_revision = '1aa0d7d9d39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('signup_date')

    # ### end Alembic commands ###
